export type ParkingSessionData = {
  /** ID generated by firestore */
  id?: string;
  /** User's phone number */
  phoneNumber: string;
  /** Car's license plate */
  licensePlate: string;
  /** Parking session start time */
  startTime: number;
  /** Parking session end time. If null, session is still active. */
  endTime: number | null;
};

export type SessionPropValidation = {
  valid: boolean;
  message: string;
};

export type SessionDataValidation = Record<
  "licensePlate" | "phoneNumber",
  SessionPropValidation
>;
